version: "3.8"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    env_file:
      - frontend/.env
    environment:
      NODE_ENV: ${NODE_ENV}
      NEXT_PUBLIC_SERVER_URL: http://localhost:8000
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
